### ISSUE TITLE
Time control

### ISSUE THREAD

**Issue by SzotsGabor** [OliverLeenders/ChessEngineVS#4]
Are you going to implement time control capability any time soon? Moving instantly makes it much weaker although I estimate it may still play at about 1200-1300 Elo level.

**Comment by OliverLeenders** [comment]
Hi there, i have a version with time control soon to be published. It is still basic but it is also significantly stronger because of improved evaluation. Just have a lookout for the next release. I suppose that will happen next week.

**Comment by SzotsGabor** [comment]
> Hi there, i have a version with time control soon to be published. It is still basic but it is also significantly stronger because of improved evaluation. Just have a lookout for the next release. I suppose that will happen next week.

Hi Oliver,

Good news. I hope it will support Fischer clock too. Anyway, I am running a tournament with 1.0 for the CCRL blitz list.

Gabor

**Comment by OliverLeenders** [comment]
Hi Gabor, 

yes Fischer Time (i.e. increment per move as far as i understand) is now supported (look at latest release -- with version number ;)). I think I can close that issue now.

Thank you for contributing by running that tournament of yours. I would be happy to see some results of that. 


Best regards
Oliver

**Comment by SzotsGabor** [comment]
> yes Fischer Time (i.e. increment per move as far as i understand) is now supported (look at latest release -- with version number ;)). I think I can close that issue now.
> 
> Thank you for contributing by running that tournament of yours. I would be happy to see some results of that.

Well, that was quick. Now you have given me a problem, shall I continue the tournament with 1.0 (66 out of 448 games played) or shall I interrupt it and start a new one with 1.1. I think I'll vote for the latter.

**Comment by OliverLeenders** [comment]
I would also recommend using 1.1 as it is considerably stronger and also has some errors in the eval corrected.
