### ISSUE TITLE
Hash size

### ISSUE THREAD

**Issue by SzotsGabor** [OliverLeenders/ChessEngineVS#5]
It should be 256 MB but Arena and Process Explorer both show it uses only 66.

**Comment by OliverLeenders** [comment]
Yes that is true. I only recently added the uci option Hash Size. It is for now a fake option which is only there to make it possible to play it as a lichess bot. I might look into how to correctly implement hash size in the future

**Comment by OliverLeenders** [comment]
The problem mainly are two issues: moving the bestmove from a heap allocated pointer to a pre-allocated nullmove and computing the size of the allocated memory

**Comment by OliverLeenders** [comment]
v1.2 implements the UCI Hash command (see releases). The programm will always use memory around the demanded MB but never more. It also fixes some bugs with null move pruning.
